# NoRegen by TheDiamondYT

# Show a message to the player on join
message:
  show: true  # Set to false to disable
  text: 'This server has health regeneration disabled.'

block:
  # Block natural regeneration
  regen: true
  
  # Block eating regeneration
  eating: true
  
  # Block potion regeneration
  potion: true
  
  # Block custom (by plugins) regeneration
  custom: true
  
  # Block hunger saturation regeneration
  saturation: true